version: '3'
services:
  db:
    build: 
      context: ./
      dockerfile: ./infra/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
  api:
    build: 
      context: ./
      dockerfile: ./infra/rails/Dockerfile
    # 本番環境
    # command: bundle exec pumactl start
    # 開発環境
    command: bash -c "bundle install && bundle exec rails s -b '0.0.0.0'"
    # command: bash -c "tail -f log/development.log"
    volumes:
      - ./rails:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  front:
    working_dir: /app/app
    build:
      context: ./
      dockerfile: ./infra/next/Dockerfile
    command: bash -c "yarn dev"
    tty: true
    stdin_open: true
    volumes:
      - ./next:/app
    ports:
      - "8000:3000"
  web:
    build: 
      context: ./
      dockerfile: ./infra/nginx/Dockerfile.prod
    ports:
      - "80:80"
    volumes:
      - ./rails:/app
    depends_on:
      - api
      - front

volumes:
  mysql_data:
# 