name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      RAILS_DEVELOPMENT_KEY: ${{ secrets.RAILS_DEVELOPMENT_KEY }}
      RAILS_TEST_KEY: ${{ secrets.RAILS_TEST_KEY }}
      RAILS_ENVIRONMENT_KEY: ${{ secrets.RAILS_ENVIRONMENT_KEY }}
    defaults:
      run:
        working-directory: rails
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby 3.1.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Bundle and gem install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle
      - name: debug
        run: |
          echo secret "${ secrets.RAILS_MASTER_KEY }" | sed 's/./& /g'
          echo secret "${ secrets.RAILS_DEVELOPMENT_KEY }" | sed 's/./& /g'
          echo secret "${ secrets.RAILS_TEST_KEY }" | sed 's/./& /g'
          echo secret "${ secrets.RAILS_ENVIRONMENT_KEY }" | sed 's/./& /g'

          ls -la config
          echo $RAILS_MASTER_KEY > config/master.key
          echo $RAILS_TEST_KEY  > config/credentials/test.key
          echo $RAILS_ENVIRONMENT_KEY > config/credentials/environment.key
          echo $RAILS_DEVELOPMENT_KEY > config/credentials/development.key
          bundle exec rails db:create 

